apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ item.metadata.name }}-client-mtls
spec:
  host: {{ item.metadata.name }}.bookinfo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
