apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ item.metadata.name }}-virtualservice
spec:
  hosts:
  - {{ item.metadata.name }}.{{openshift_apps_domain}}
  gateways:
  - bookinfo-wildcard-gateway.{{control_plane_project_name}}.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9080
        host: {{ item.metadata.name }}.{{service_mesh_member_roll_namespaces}}.svc.cluster.local
